Added fan support, proper timeouts for commands
SergejPr/NooLite-F pull request #3
Opened 2018-07-26 11:03 UTC by mrukavishnikov

According to NooLite developers commands are sent on about 50ms (1 to send, 1 to receive response, and the same for repeating command)

2018-07-26 16:06 UTC, SergejPr requested changes
Hi, thanks for adding new functionality. However I have left some comments. Please see them.

2018-07-26 16:06 UTC, SergejPr commented on NooLite_F/MTRF64/MTRF64Controller.py
> +from NooLite_F import NooLiteFController, BrightnessDirection, BrightnessDirection, ModuleMode, RemoteControllerListener, BatteryState
There is a duplication of BrightnessDirection.

2018-07-26 16:06 UTC, SergejPr commented on NooLite_F/NooLiteFController.py
> +                       module_mode: ModuleMode = ModuleMode.NOOLITE_F) -> List[ResponseBaseInfo]:
All these functions and their implementation are the duplication of the brightness function. The main idea of this class is hi level interface for all API commands. Api isn't provided speed commands, only brightness. So I don't see any sence in these methods. You can use brightness functions directly in your fan module the same way as you use dimmer configuration functions.

2018-07-27 09:52 UTC, mrukavishnikov commented on NooLite_F/NooLiteFController.py
> +                       module_mode: ModuleMode = ModuleMode.NOOLITE_F) -> List[ResponseBaseInfo]:
Sure, but HA will think about it as a light, not a fan.

2018-07-27 14:41 UTC, SergejPr commented on NooLite_F/NooLiteFController.py
> +                       module_mode: ModuleMode = ModuleMode.NOOLITE_F) -> List[ResponseBaseInfo]:
No, you will left your HA Fan module without changes, exclude call of NooLite module methods. For example, insted of  
```
responses = DEVICE.set_speed(int_speed / 255, None, self._config.get(CONF_CHANNEL),
                                     self._config.get(CONF_BROADCAST), _module_mode(self._config))
``` 
you will call 
```
responses = DEVICE.set_brightness(brightness / 255, None, self._config.get(CONF_CHANNEL),
                                          self._config.get(CONF_BROADCAST), _module_mode(self._config))
``` 
As result HA will thinks that works with fan, but will use brightness method for setting output voltage level.

2018-07-27 14:46 UTC, SergejPr commented on NooLite_F/NooLiteFController.py
> +                       module_mode: ModuleMode = ModuleMode.NOOLITE_F) -> List[ResponseBaseInfo]:
If you don't mind I can merge your changes and update it according to my point of view.

2018-07-30 14:44 UTC, merged